# Copyright 2020 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM photon:5.0
COPY /bin/linux/amd64/lib/vmware-vix-disklib/lib64/* /vddkLibs/
ADD /bin/linux/amd64/backup-driver* /backup-driver
ENTRYPOINT ["/backup-driver"]
