# Copyright 2017, 2019 the Velero contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM busybox:1.33.1 AS busybox

FROM photon:5.0
ADD /bin/linux/amd64/data-* /datamgr
COPY /bin/linux/amd64/lib/vmware-vix-disklib/lib64/* /vddkLibs/
COPY --from=busybox /bin/sh /bin/sh
COPY --from=busybox /bin/cp /bin/cp
COPY --from=busybox /bin/tar /bin/tar
COPY --from=busybox /bin/ls /bin/ls
ENTRYPOINT ["/datamgr"]
